"""Removed content column from Todo

Revision ID: 2ed82958a7be
Revises: 6d10fa0a9ec1
Create Date: 2024-04-26 21:31:44.646855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed82958a7be'
down_revision = '6d10fa0a9ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
